[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
rifgen = "*"
jni-sys = "*"
#logging
log = "*"
log-panics = "*"
android_logger = "*"
deno_core = "*"

[build-dependencies]
flapigen = "0.6.0-pre9"
rifgen = "*"

[lib]
name = "rust_lib"
crate-type = ["cdylib"]
