#Cross 交叉编译容器构建工具：https://github.com/cross-rs/cross/wiki/Configuration
[build]
build-std = false # do not build the std library. has precedence over xargo
default-target = "aarch64-linux-android" # use this target if none is explicitly provided
# pre-build = [
#   # additional commands to run prior to building the package
#   "dpkg --add-architecture $CROSS_DEB_ARCH",
#   "apt-get update && apt-get --assume-yes install libssl-dev:$CROSS_DEB_ARCH",
# ] 
xargo = true # enable the use of xargo by default

[target.aarch64-linux-android]
image = "cross:aarch64-linux-android-0.2.1"

[build.env]
passthrough = [
  "V8_FROM_SOURCE",
  "SCCACHE_ERROR_LOG",
  "SCCACHE_LOG",
  "SCCACHE_DIR",
  "SCCACHE_IDLE_TIMEOUT",
]

[target.aarch64-linux-android.env]
passthrough = ["RUSTY_V8_MIRROR=VALUE", "RUSTY_V8_ARCHIVE=VALUE"]
volumes = [
  "RUSTY_V8_MIRROR=/Users/mac/Desktop/waterbang/project/android-deno-runtime-example/rust_lib/assets/rusty_v8_mirror/",
  "RUSTY_V8_ARCHIVE=/Users/mac/Desktop/waterbang/project/android-deno-runtime-example/rust_lib/assets/rusty_v8_mirror/v0.42.0/librusty_v8_release_aarch64-linux-android.a",
]
