/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bfchain_rust_plaoc_MainActivity_Companion */

#ifndef _Included_org_bfchain_rust_plaoc_MainActivity_Companion
#define _Included_org_bfchain_rust_plaoc_MainActivity_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
