// Automatically generated by flapigen
package org.bfchain.rust.example.lib;


public final class RustLog {

    public static native void initialiseLogging();

    public static native void testV8();

    private RustLog() {}
}